import Head from "next/head";
import {
  AiOutlineGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import sebAvatar from "../public/avatarS.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        {/* <section className="min-h-screen"> */}
          <nav className="sticky top-0 z-50 py-10 mb-12 flex justify-between bg-white dark:bg-gray-900 px-2 md:px-20 lg:px-0 dark:text-white">
            <h1 className="font-burtons text-xl">SebastianDev</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl mr-10"
                />
              </li>
              <li>
                <a
                  className="font-burtons text-xl mr-4"
                  href="#"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  className="font-burtons text-xl mr-4"
                  href="#"
                >
                  Projects
                </a>
              </li>
              <li>
                <a
                  className="font-burtons text-xl"
                  href="#"
                >
                  Contact
                </a>
              </li>
            </ul>
          </nav>
          
    <section className="text-center p-10 py-10">
    <div className="flex flex-col md:flex-row items-center justify-center text-left">
      <div className="mb-6 md:mb-0 md:mr-8">
    <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
      Sebastian Buritica
    </h2>
    <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
    Full stack developer.
    </h3>
    <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:mx-0 md:text-xl">
    Full-stack developer specializing in responsive websites, efficient back-end solutions, and mobile applications. Dedicated to delivering high-quality code and user-centered design.
    </p>
    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
      <AiOutlineGithub />
    </div>
    </div>
    <div className="avatar-bounce w-48 h-48 sm:w-64 sm:h-64 md:w-96 md:h-96 rounded-full overflow-hidden relative">
        <Image src={sebAvatar} layout="fill" objectFit="cover" />
      </div>
    </div>
  </section>

        {/* </section> */}
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
